---
title: "About our data"
---

For our exploratory study we used 6 datasets. All data was retrieved from [New York State DOH HealthData](https://data.ny.gov/browse?category=Health&utf8=%E2%9C%93), [NYCDOH Environment and Health Data Portal](http://a816-dohbesp.nyc.gov/IndicatorPublic/publictracking.aspx), and [United States Environmental Protection Agency AirData](https://www.epa.gov/outdoor-air-quality-data).

* [Asthma emergency department visits](https://health.data.ny.gov/Health/PA-Asthma-Emergency-Department-Visit-Rate-Per-10-0/4xmh-bgkz) data was used to obtain county-level rates of asthma emergency department visits per 10,000 for the state of New York in 2014.  

* [Age-adjusted cardiovascular disease hospitalization](https://health.data.ny.gov/Health/Community-Health-Age-adjusted-Cardiovascular-Disea/3ycx-tfnb) data was used to obtain county-level rates of cardiovascular disease hospitalization visits per 10,000 for the state of New York between 2012 and 2014. This dataset was age-adjusted since the risk of developing cardiovascular disease increases with age.

* [PM 2.5](https://apps.health.ny.gov/statistics/environmental/public_health_tracking/tracker/index.html#/airpollutionExportData) data was used to obtain annual average fine particulate matter concentration by county for the state of New York between 2000 and 2017.

* [Ozone](https://apps.health.ny.gov/statistics/environmental/public_health_tracking/tracker/index.html#/airpollutionExportData) data was used to obtain  both number of days and person-days with maximum eight-hour average concentration above the National Ambient Air Quality Standard (0.070 parts per million) by county (with ozone air monitoring) for the state of New York between 2000 and 2016.

* [Annual summary air quality index](https://aqs.epa.gov/aqsweb/airdata/download_files.html#Annual) data was used to obtain the number of days with recorded Air Quality Index (AQI) values, subsequent number of days per level of health concern (good, moderate, unhealthy for sensitive groups, unhealthy, very unhealthy, and hazardous), and median AQI values for all counties in the United States in 2014.

* [NYS hospitals](https://profiles.health.ny.gov/hospital/county_or_region/) data was used to obtain the number of hospitals per county in New York.